name: Test
on:
  - pull_request
  - push

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ginkgo
        run: go get -u github.com/onsi/ginkgo/ginkgo
      - name: Run tests
        run: ginkgo -r
